#This will configure services for Kafka, Spark, and PostgreSQL.

version: '3.8'

services:
  spark:
    build: ./spark
    container_name: spark-container
    environment:
      SPARK_MASTER: "spark://spark-container:7077"
    ports:
      - "4040:4040"  # Spark UI
      - "7077:7077"  # Spark master
    volumes:
      - ./data:/data  # Mount data directory

  postgres:
    image: postgres:latest
    container_name: postgres-container
    environment:
      POSTGRES_USER: hk3
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: salesdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  python:
    build: .
    container_name: python-container
    depends_on:
      - spark
      - postgres
    volumes:
      - ./data:/data  # Mount data directory for access
    entrypoint: /bin/bash

volumes:
  postgres_data:
